---

- hosts: 192.168.33.32
  tasks:
  - name: delete a user
    mongodb_user:
      database: "zephyr-test"
      name: "admin"
      password: "admin"
      roles: "readWrite"
      state: absent
      login_user: "sauron"
      login_password: "gorthaur"
      login_port: "{{ mongodb_login_port|default(27017) }}"
      login_host: 192.168.33.20
